# -*- coding: utf-8 -*-
"""iolearn_j2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gUJZTLjLxfN0Kn6YAAPa8mrQBTGjK67q
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from tensorflow import keras
from PIL import Image
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout

face_model=cv2.CascadeClassifier('aiolearn.xml')
image=cv2.imread('mokhtari.jpg')
plt.imshow(image)

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces=face_model.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30,30))
plt.imshow(gray)
plt.imshow(image)

image2=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
plt.imshow(image2)

print(f'tedad faces : {len(faces)}')

for (x,y,w,h) in faces:
  cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
plt.imshow(image)

nima2=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
plt.imshow(image)

